### ISSUE TITLE
Footnote can obscure verse

### ISSUE THREAD

**Issue by kuzunguka** [mimbrown/render#107]
Suggestion.  If I click on a footnote marker in a verse near the bottom of my screen, the verse can be obscured by the footnote pop-up.  For short footnotes this doesn't seem to be a problem.  But for long footnotes, such as in Matt 5:17, by the time a reader is partway through or all the way through reading the footnote, it might be nice for them to be able to see the verse at the same time without losing the footnote.  In addition, after reading such a long footnote, it would be easier for them to find their place back in the text if their position on the screen was still visible rather than obscured.

**Comment by mnjames** [comment]
This doesn't bother me, but I am also in no way opposed to it. I would suggest putting this off until Michael has more time to work on it or decides it's not possible.

**Comment by socvid** [comment]
This doesn't bother me either, and this request is impossible to fulfill without the verse being scrollable.  If you use a large font size (not to mention if you have a smaller resolution screen) then there is no way you will be able to fit Matt 5:17 in the top half of your screen.  So you would have to make the verse scrollable, and now your way of closing the popup is gone...  So now we would need a close button or a split screen implementation like KiM.

If I were to change anything with the footnotes it would be to allow them take up to 3/4 of the screen instead of half so that you don't have to scroll as much.  If the other popups can be that large, then whey not footnotes?  This would mean you definitely wouldn't be able to see the verse, which I am fine with because you can so quickly close and open the footnote in the probably rare cases one would want to go back and forth.

The popup design is a really intuitive design that doesn't facilitate scrolling in the content behind it.  The verse is darkened to bring your eyes to the popup and keep them there.  It clearly shows what text is from the footnote and what isn't.  The darkness also communicates to the user that they need to tap out of the footnote in the verse to remove the popup and then they can continue reading.  In my opinion this is overcomplicating what this is designed to do.  Books and Apps both have strengths and weakness, and this is a weakness of Apps that you can't see a lot of things at once.

If we did want to try to make this work then one option would be to use a split screen design, but I have always hated trying to manipulate split screens on phones (like the one in KiM).  The sliding bar can be hard to touch and move to set different proportions of verse:footnote size, and returning to normal view (via a menu, or via touch and moving the bar all the way down off the screen, or via two finger touch in one side) can be difficult and/or unintuitive.  The advantage of split screen is that you can scroll in both and they are clearly divided.

Another option is including the verse in the footnote, but you don't want to see the verse first.  You want to read the footnote.

All of these reasons is probably why YouVersion opens the footnotes in a box within the text.  It is a pretty clever idea, but it may be seen as strange to a lot of people.

**Comment by kuzunguka** [comment]
I think the reason I thought of this is because I'm using a large screen.  I can see that on a more normal-sized phone screen, especially if the user has increased the text size, many times the verse where the footnote came from would have to be obscured.  So I suggest we close this for now.
