### ISSUE TITLE
Handling usx from Paratext 9

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#57]
This is low priority--it would simply save me a little time when I happen to be working in Paratext 9 instead of Paratext 8.

The new version of Paratext 9 outputs usx in a slightly different format. In particular, it has attributes named:
sid="xxx"
eid="xxx"
(I think that's all).

The attribute and the references in the "xxx" marks can be ignored, but currently they're not being ignored and thus are causing problems.

Old version (MAT): 
[SSV.usx.txt](https://github.com/mimbrown/render/files/3047355/SSV.usx.txt)
New version:
[PT9.usx.txt](https://github.com/mimbrown/render/files/3047356/PT9.usx.txt)

**Comment by mimbrown** [comment]
As far as I can understand, the output from P9 now unambiguously marks the beginning and the ending of verses. I can make it so that it can handle outputs from both P8 and P9, but if you're going to start outputting only from P9, then that would actually simplify our code and possibly prevent mistakes, because we would not have to try to find where the beginning and ending of verses is. Are you going to be using P9 from here on out?

**Comment by mnjames** [comment]
I'd _like_ the option of using both. I still use both regularly, and it would be nice to just output from whichever one I happen to be using (PT9 is just a beta version which I'm using for testing purposes).

However, if there are good reasons from a data standpoint for using the PT9 output, we can certainly switch to just using that. It usually only takes a minute or two to switch programs, so it's not too difficult. And I'm not outputting new data as often as I was a couple of weeks ago.

**Comment by mimbrown** [comment]
Added support for PT9.
