### ISSUE TITLE
Footnote numbering

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#6]
Footnote numbers increment correctly in the SSV (idiomatic) section, but down below in the footnote section they don't. Once a new page is created the correct number is used for the first footnote of the following page.

For example, in a John printout I made, on p.1, the SSV has footnotes #1-#4, but down below they are numbered 1,1,1,2. On the next page footnotes #5-7 are numbered 5,5,8. On p.3 footnotes 8-10 are numbered 10,11,13, etc.

**Comment by mimbrown** [comment]
I made it so that the footnotes match now, but I wasn't sure if you still wanted the verse that starts each footnote to be present? Each footnote starts with something like `<char style="fr" closed="false">8‏:12 </char>`. Currently only the verse is being rendered, and the Arabic style verse marker is also added. Is this how you want it?

**Comment by mnjames** [comment]
When you said "Currently only the verse is being rendered" did you mean "currently only the footnote marker number is being rendered"?
Yes, the footnote information in the usfm/xml files include the verse number the footnote falls in, and we don't want that verse number showing up down below in the footnote section.

**Comment by mimbrown** [comment]
Understood. That's been stripped out now.

**Comment by mnjames** [comment]
After writing my recommendation above, the team asked if the chapter:verse references at the "fr" code could be included temporarily before the footnote number. This would make it easier for them to find the footnote in Paratext and make edits when they're doing checking work.
